# -*- coding: utf-8 -*-
"""tugasSistemTemuKembali (8).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JupH9qhMJE6dgaXQxDw52c_Klh-X2-nC

INSTALISASI DAN IMPORT LIBRARY
"""

pip install sastrawi

import requests
import re
import time
import pickle
import numpy as np
import pandas as pd
import urllib.parse
import urllib.request

from bs4 import BeautifulSoup
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

"""SCRAPING DATA"""

urls = [
"https://nasional.kompas.com/read/2026/03/09/17303561/prabowo-ingatkan-rakyat-indonesia-bersiap-hadapi-kesulitan-akibat-perang",
    "https://nasional.kompas.com/read/2026/03/10/13125731/memahami-kerja-ombudsman-di-tengah-penggeledahan-terkait-kasus-cpo",
    "https://nasional.kompas.com/read/2026/03/10/12344451/puan-sebut-dpr-dukung-pembatasan-medsos-untuk-anak-agar-tak-kebablasan",
    "https://nasional.kompas.com/read/2026/03/06/20503101/klarifikasi-bahlil-soal-stok-bbm-sisa-20-hari-yang-bikin-warga-panic-buying",
    "https://regional.kompas.com/read/2026/03/06/135609978/jokowi-ungkap-isi-pertemuan-dengan-prabowo-di-istana-bahas-bop-dan-tarif",
    "https://nasional.kompas.com/read/2026/03/09/11502271/kejagung-geledah-kantor-dan-rumah-komisioner-ombudsman-terkait-kasus-cpo",
    "https://nasional.kompas.com/read/2026/03/10/07193531/polri-jelaskan-simulator-berkuda-yang-viral-harganya-rp-1-miliar.",
    "https://nasional.kompas.com/read/2026/03/10/09142961/dua-ott-dalam-seminggu-dua-bupati-ditangkap-kpk.",
    "https://nasional.kompas.com/read/2026/03/10/09411181/kpk-periksa-ketum-pp-japto-soerjosoemarno-jadi-saksi-kasus-gratifikasi.",
    "https://nasional.kompas.com/read/2026/03/06/20471631/semarakkan-ramadhan-kasatgas-tito-salurkan-bantuan-untuk-puluhan-ribu-korban",
    "https://money.kompas.com/read/2026/03/01/055816426/daftar-harga-bbm-terbaru-1-maret-2026-di-seluruh-indonesia",
    "https://money.kompas.com/read/2026/03/07/080016726/cek-harga-pertamax-hari-ini-7-maret-2026-di-spbu-seluruh-indonesia",
    "https://money.kompas.com/read/2026/03/10/204239226/bni-bbni-tebar-dividen-rp-1303-t-analis-soroti-sinyal-stabilitas",
    "https://money.kompas.com/read/2026/03/09/170101426/imbas-fitch-turunkan-outlook-indonesia-investor-mulai-khawatir-kebijakan",
    "https://money.kompas.com/read/2026/03/04/204140126/menkeu-as-tarif-global-15-persen-kemungkinan-berlaku-minggu-ini",
    "https://money.kompas.com/read/2026/03/10/123716426/wifi-dan-nokia-jajaki-pengembangan-infrastruktur-digital-6g",
    "https://money.kompas.com/read/2026/03/07/075736926/harga-emas-di-pegadaian-7-maret-2026-galeri-24-dan-ubs-stabil",
    "https://money.kompas.com/read/2026/03/10/120912026/harga-emas-pegadaian-hari-ini-10-3-kompak-menguat-cek-daftar-ubs-galeri-24",
    "https://money.kompas.com/read/2026/03/04/202228826/selat-hormuz-bergejolak-pengalihan-impor-minyak-ke-as-jadi-alternatif",
    "https://money.kompas.com/read/2026/03/10/040400926/120-juta-unit-sepeda-motor-bensin-dikonversi-ke-listrik-bahlil--untuk-kurangi.",
    "https://tekno.kompas.com/read/2026/03/10/08040087/nintendo-gugat-as-minta-uang-tarif-impor-trump-dikembalikan",
    "https://tekno.kompas.com/read/2026/03/10/07000057/ini-dia-hiroh-phone-hp-yang-punya-tombol-fisik-darurat-untuk-anti-sadap",
    "https://tekno.kompas.com/read/2026/03/09/12240037/daftar-harga-iphone-terbaru-9-maret-2026-iphone-13-iphone-17-series",
    "https://tekno.kompas.com/read/2026/03/09/11220057/8-aplikasi-yang-dilarang-komdigi-buat-diakses-anak-anak-di-bawah-16-tahun",
    "https://tekno.kompas.com/read/2026/03/08/15030037/china-bikin-baterai-nuklir-mini-bisa-tahan-50-tahun-tanpa-dicas.",
    "https://money.kompas.com/read/2026/02/16/162901226/memutus-kutukan-generasi-ketiga-mengapa-hong-kong-jadi-opsi-strategis-bagi?source=pilihanuntukmu&medium=pos2&campaign=CM.",
    "https://tekno.kompas.com/read/2026/03/01/19070037/populasi-robot-ai-diprediksi-meledak-pekerja-manusia-makin-terdesak.",
    "https://tekno.kompas.com/read/2026/03/07/14030087/robot-humanoid-mulai-kerja-di-pabrik-xiaomi.",
    "https://regional.kompas.com/read/2026/03/05/161743778/tni-gerebek-tambang-emas-ilegal-di-madina-6-ekskavator-dan-pekerja",
    "https://surabaya.kompas.com/read/2026/03/10/084602278/kesehatan-menurun-selama-ditahan-terdakwa-pembunuhan-bocah-sd-di-pasuruan",
    "https://surabaya.kompas.com/read/2026/03/10/081939978/pengusaha-parsel-di-surabaya-mengeluh-sepi-dulu-terjual-1000-per-hari-kini",
    "https://regional.kompas.com/read/2026/03/06/134815078/desa-di-kendal-ini-bagikan-thr-ke-warga-setiap-kk-dapat-rp-1-juta",
    "https://regional.kompas.com/read/2026/03/09/193016078/dorong-pad-pemprov-maluku-siapkan-kepulauan-lucipara-jadi-wisata-bahari",
    "https://bandung.kompas.com/read/2026/03/08/115715478/peringatan-nuzulul-quran-2000-al-quran-akan-disalurkan-ke-warga-bogor",
    "https://regional.kompas.com/read/2026/03/10/151404778/napi-lapas-nusakambangan-kabur-hingga-menyeberang-pulau-ujungnya-ditangkap.",
    "https://megapolitan.kompas.com/read/2026/03/09/11560641/cuaca-ekstrem-diprediksi-terjadi-hingga-12-maret-jakarta-masuk-wilayah",
    "https://megapolitan.kompas.com/read/2026/03/09/17075531/detik-detik-warga-periuk-damai-diterjang-banjir-air-datang-tiba-tiba-saat",
    "https://megapolitan.kompas.com/read/2026/03/10/07230411/saat-peringatan-prabowo-soal-sampah-bantargebang-jadi-kenyataan.",
    "https://internasional.kompas.com/read/2026/03/10/061605970/trump-isyaratkan-segera-akhiri-perang-klaim-iran-sudah-lumpuh",
    "https://lestari.kompas.com/read/2026/03/10/081200786/china-targetkan-pangkas-intensitas-karbon-17-persen-pada-2030",
    "https://internasional.kompas.com/read/2026/03/09/080000170/as-disebut-kecewa-israel-gempur-30-pangkalan-minyak-iran-anggap.",
    "https://internasional.kompas.com/read/2026/03/09/050356570/resmi-ayatollah-mojtaba-khamenei-terpilih-jadi-pemimpin-tertinggi-iran.",
    "https://lestari.kompas.com/read/2026/03/09/075648886/klh-tuang-10000-liter-ecoenzym-ke-sungai-cisadane-netralkan-cemaran",
    "https://lestari.kompas.com/read/2026/03/08/150422386/perang-emisi-dan-masa-depan-bumi",
    "https://lestari.kompas.com/read/2026/03/09/161005186/akan-dibor-tahun-ini-pge-siapkan-infrastruktur-pltp-lumut-balai-unit-3",
    "https://lestari.kompas.com/read/2026/03/10/130200086/bab-baru-nilai-ekonomi-karbon",
    "https://lestari.kompas.com/read/2026/03/09/194800786/sering-cek-email-kerja-saat-akhir-pekan-waspada-dampaknya-untuk-mental",
    "https://travel.kompas.com/read/2026/03/09/060600827/7-wisata-sejarah-di-kota-semarang-sudah-ada-yang-dari-abad-ke-17. ",
    "https://bandung.kompas.com/read/2026/02/25/204040778/truk-terparkir-seharian-di-bandung-sopir-ternyata-meninggal-di-kabin.",
    "https://travel.kompas.com/read/2026/03/10/050500427/jadwal-dan-harga-tiket-kereta-wisata-ambarawa-saat-libur-lebaran-18-31-maret."
]

headers = {
    "User-Agent": "Mozilla/5.0"
}

data = []
no = 1

for url in urls:

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.text, "html.parser")

    judul = soup.find("h1").get_text()

    content = soup.find("div", {"class":"read__content"})

    text = ""
    if content:
        paragraf = content.find_all("p")
        text = " ".join([p.get_text() for p in paragraf])

    data.append([no, url, judul, text])

    no += 1

    time.sleep(2)

df = pd.DataFrame(data, columns=["No", "URL", "Judul", "Text"])
df

df.to_excel("dataset_berita.xlsx", index=False)

from google.colab import files
files.download("dataset_berita.xlsx")



df = pd.read_excel("dataset_berita.xlsx")
df.head()

"""PREPROCESSING TEKS"""

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text) # hapus link
    text = re.sub(r'[^a-zA-Z\s]', '', text) # hapus angka & simbol
    text = re.sub(r'\s+', ' ', text)    # hapus spasi berlebih
    return text

df["clean_text"] = df["Text"].apply(clean_text)

factory = StopWordRemoverFactory()
stopword = factory.create_stop_word_remover()

df["clean_text"] = df["clean_text"].apply(lambda x: stopword.remove(x))

factory = StemmerFactory()
stemmer = factory.create_stemmer()

df["clean_text"] = df["clean_text"].apply(lambda x: stemmer.stem(x))

df_kalimat = df[["clean_text"]]

df_kalimat.to_excel("preprocessing_kalimat.xlsx", index=False)

from google.colab import files
files.download("preprocessing_kalimat.xlsx")

df["token"] = df["clean_text"].apply(lambda x: x.split())

df_token = df[["No","token"]].explode("token")

df_token.to_excel("token_perkata.xlsx", index=False)

from google.colab import files
files.download("token_perkata.xlsx")

"""PEMBOBOTAN TF-IDF"""

processed_paper = df["clean_text"].tolist()

words = list(set(" ".join(processed_paper).split()))
print("Jumlah dokumen:", len(processed_paper))
print("Jumlah kata unik:", len(words))

with open("processed_paper.pkl", "wb") as f:
    pickle.dump(processed_paper, f)

with open("words.pkl", "wb") as f:
    pickle.dump(words, f)

print("Berhasil disimpan.")

vectorizer = TfidfVectorizer(use_idf=True)
tfidf_matrix = vectorizer.fit_transform(processed_paper)
print("Shape TF-IDF matrix:", tfidf_matrix.shape)

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

init_query = "harga emas"  # masukkan query

query = init_query.lower()
query = re.sub(r'[^a-zA-Z\s]', '', query)
query = stopword.remove(query)
query = query.split()
query = [stemmer.stem(w) for w in query]
print("Query setelah preprocessing:", ' '.join(query))

q_vec = vectorizer.transform([' '.join(query)])
result = cosine_similarity(tfidf_matrix, q_vec)

idx = np.argsort(-result, axis=0).flatten()

print("Top 5 berita paling relevan:\n")
for i in idx[:5]:
    score = result[i][0]
    if score > 0:
        print(f"[Dokumen {i+1}] Score: {score:.4f}")
        print("Judul :", df['Judul'].iloc[i])
        print("URL   :", df['URL'].iloc[i])
        print()

"""QUERY EXPANSION"""

thesaurus = {}

def get_sinonim(kata):
    try:
        data = {"q": kata}
        encoded_data = urllib.parse.urlencode(data).encode("utf-8")
        content = urllib.request.urlopen("http://www.sinonimkata.com/search.php", encoded_data)
        soup = BeautifulSoup(content, 'html.parser')
        synonym = soup.find('td', attrs={'width': '90%'}).find_all('a')
        synonym = [x.getText() for x in synonym]
        return [kata] + synonym
    except:
        return [kata]

def filter_sinonim_dinamis(kata, sinonim_list, query_words, vectorizer, tfidf_matrix, top_n=3, threshold=0.7):

    query_asli = " ".join(query_words)
    q_asli_vec = vectorizer.transform([query_asli])
    result_asli = cosine_similarity(tfidf_matrix, q_asli_vec).flatten()

    hasil = []
    idx_kata = query_words.index(kata)

    for s in sinonim_list:
        if s == kata:
            hasil.append((s, 1.0))
            continue

        query_variasi = query_words.copy()
        query_variasi[idx_kata] = stemmer.stem(s)
        q_variasi_str = " ".join(query_variasi)

        q_var_vec = vectorizer.transform([q_variasi_str])
        result_variasi = cosine_similarity(tfidf_matrix, q_var_vec).flatten()

        norm_asli = np.linalg.norm(result_asli)
        norm_var = np.linalg.norm(result_variasi)

        if norm_asli > 0 and norm_var > 0:
            skor = np.dot(result_asli, result_variasi) / (norm_asli * norm_var)
        else:
            skor = 0.0

        if skor >= threshold:
            hasil.append((s, skor))

    hasil = sorted(hasil, key=lambda x: x[1], reverse=True)
    return [x[0] for x in hasil[:top_n]]

model = SentenceTransformer('firqaaa/indo-sentence-bert-base')

def filter_sinonim_semantik(kata, sinonim_list, query_words, top_n=3, threshold=0.6):
    query_asli = " ".join(query_words)

    emb_asli = model.encode([query_asli])

    hasil = []
    idx_kata = query_words.index(kata)

    for s in sinonim_list:

        query_variasi = query_words.copy()
        query_variasi[idx_kata] = s
        q_variasi_str = " ".join(query_variasi)

        emb_variasi = model.encode([q_variasi_str])

        skor = cosine_similarity(emb_asli, emb_variasi)[0][0]

        print(f"  '{q_variasi_str}' → skor semantik: {skor:.4f}")

        if skor >= threshold:
            hasil.append((s, skor))

    hasil = sorted(hasil, key=lambda x: x[1], reverse=True)
    return [x[0] for x in hasil[:top_n]]

init_query = "narapidana lapas kabur"  # masukkan query

query = init_query.lower()
query = re.sub(r'[^a-zA-Z\s]', '', query)
query = stopword.remove(query)
query = query.split()
query = [stemmer.stem(w) for w in query]

print("Query awal:", ' '.join(query))

list_synonym = []
for kata in query:
    if kata in thesaurus:
        sinonim = thesaurus[kata]
    else:
        sinonim = get_sinonim(kata)
        thesaurus[kata] = sinonim

    sinonim = filter_sinonim_semantik(kata, sinonim, query, top_n=3, threshold=0.79)
    list_synonym.append(sinonim)

for i, kata in enumerate(query):
    print(f"Sinonim '{kata}':", list_synonym[i])

qs = set()

for i, kata in enumerate(query):
    for s in list_synonym[i]:
        kombinasi = query.copy()
        kombinasi[i] = s
        qs.add(' '.join(kombinasi))

qs.add(' '.join(query))

print("\nSemua kombinasi query:")
for q in qs:
    print("-", q)

max_result = []
THRESHOLD = 0.1

for q in qs:
    q_vec = vectorizer.transform([q])
    result = cosine_similarity(tfidf_matrix, q_vec)
    final = [[i, result[i][0], q] for i in range(len(result)) if result[i][0] > THRESHOLD]
    max_result += final

max_result = sorted(max_result, key=lambda x: x[1], reverse=True)

set_result = set()
new_result = []
for item in max_result:
    if item[0] not in set_result:
        set_result.add(item[0])
        new_result.append(item)

print(f"Jumlah berita ditemukan: {len(new_result)}")
print("\nBerita paling relevan (dengan Query Expansion):\n")
for item in new_result[:50]:
    i, score, q_used = item
    print(f"[Dokumen {i+1}] Score: {score:.4f} | Query: '{q_used}'")
    print("Judul :", df['Judul'].iloc[i])
    print("URL   :", df['URL'].iloc[i])
    print()

THRESHOLD = 0.1  # satu threshold, dipakai konsisten di mana-mana

relevant_docs = set()
retrieved_docs = set()


q_vec_asli = vectorizer.transform([' '.join(query)])
for i in range(len(processed_paper)):
    skor = cosine_similarity(tfidf_matrix[i], q_vec_asli)[0][0]
    if skor >= THRESHOLD:
        relevant_docs.add(i)

for item in new_result:
    i, score, q_used = item
    if score >= THRESHOLD:
        retrieved_docs.add(i)

true_positive = relevant_docs & retrieved_docs
precision = len(true_positive) / len(retrieved_docs) if retrieved_docs else 0
recall = len(true_positive) / len(relevant_docs) if relevant_docs else 0
f1 = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

print(f"Relevant docs  : {relevant_docs}")
print(f"Retrieved docs : {retrieved_docs}")
print(f"True Positive  : {true_positive}")
print(f"Precision      : {precision:.4f}")
print(f"Recall         : {recall:.4f}")
print(f"F1-Score       : {f1:.4f}")